### ISSUE TITLE
How wo extract the quadrangulated mesh?

### ISSUE THREAD

**Issue by bootsmakes** [mlivesu/topological_IGM#1]
Hi, is there a way to extract the quadrangulated mesh?

**Comment by mlivesu** [comment]
hi, the code I provided is meant to show the quadmesh as a checkerboard texture. If you want to build a real quadrilateral mesh you should essentially do the same thing that I do in `bilinear_texturing`, but rather than storing uv texture coordinates you want to store the associated sample points in the mesh. Everything that is needed is inside that function already

**Comment by bootsmakes** [comment]
The 'edge lengths' in the checkerboard texture aren't uniform, is there a way to specify or constrain it so that the quads are of similar size?

**Comment by mlivesu** [comment]
the topological pattern that I use to ensure mesh conformity necessitates edges of uneven length

**Comment by bootsmakes** [comment]
I see. Thanks!
